apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  labels:
    app: app-1
  namespace: namespace-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: apache
        image: bitnami/apache:latest
        ports:
        - name: apache
          containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /opt/bitnami/apache/conf/bitnami/bitnami.conf
          subPath: bitnami.conf
        - name: config
          mountPath: /app/index.html
          subPath: index.html
      - name: apache-exporter
        args: 
        - --scrape_uri=http://localhost:8080/server-status/?auto
        image: bitnami/apache-exporter:latest
        ports:
        - name: prometheus
          containerPort: 9117
      volumes:
      - name: config
        configMap:
          name: app-1
