apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: namespace-1
spec:
  ports:
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: prometheus
  - name: sidecar
    port: 9091
    protocol: TCP
    targetPort: sidecar
  selector:
    app: prometheus
