apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  annotations:
    iam.gke.io/gcp-service-account: prometheus@red-forklift-301112.iam.gserviceaccount.com
  labels:
    app: prometheus
  namespace: namespace-1
