apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: namespace-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/data
        image: prom/prometheus:latest
        ports:
        - name: prometheus
          containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: data-volume
          mountPath: /data
      - name: sidecar
        image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.8.0
        args:
        - --stackdriver.project-id=red-forklift-301112
        - --prometheus.wal-directory=/data/wal
        - --prometheus.api-address=http://127.0.0.1:9090
        - --stackdriver.kubernetes.location=us-central1
        - --stackdriver.kubernetes.cluster-name=cluster-1
        ports:
        - name: sidecar
          containerPort: 9091
        volumeMounts:
        - name: data-volume
          mountPath: /data
      serviceAccountName: prometheus
      volumes:
       - name: config
         configMap:
           name: prometheus 
       - name: data-volume
         emptyDir: {}
