apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
  labels:
    app: app-1
  namespace: namespace-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: apache
        image: bitnami/apache:latest
        ports:
        - name: apache
          containerPort: 8080
        resources:
          limits:
            memory: 16Mi
            cpu: 60m
          requests:
            memory: 16Mi
            cpu: 40m
        volumeMounts:
        - name: config
          mountPath: /opt/bitnami/apache/conf/bitnami/bitnami.conf
          subPath: bitnami.conf
        - name: config
          mountPath: /app/index.html
          subPath: index.html
      volumes:
      - name: config
        configMap:
          name: app-1

